apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ingress
spec:
  type: ingress
  replicas: 2
  proxyClass: direct
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: direct
spec:
  staticEndpoints:
    nodePort:
      ports:
        - port: 31667
          endPort: 31680
      selector:
        kubernetes.io/os: linux
